export enum AwsManagedRuleGroup {
  AWSManagedRulesCommonRuleSet = 'AWSManagedRulesCommonRuleSet',
  AWSManagedRulesAdminProtectionRuleSet = 'AWSManagedRulesAdminProtectionRuleSet',
  AWSManagedRulesKnownBadInputsRuleSet = 'AWSManagedRulesKnownBadInputsRuleSet',
  AWSManagedRulesSQLiRuleSet = 'AWSManagedRulesSQLiRuleSet',
  AWSManagedRulesLinuxRuleSet = 'AWSManagedRulesLinuxRuleSet',
  AWSManagedRulesUnixRuleSet = 'AWSManagedRulesUnixRuleSet',
  AWSManagedRulesWindowsRuleSet = 'AWSManagedRulesWindowsRuleSet',
  AWSManagedRulesPHPRuleSet = 'AWSManagedRulesPHPRuleSet',
  AWSManagedRulesWordPressRuleSet = 'AWSManagedRulesWordPressRuleSet',
  AWSManagedRulesAmazonIpReputationList = 'AWSManagedRulesAmazonIpReputationList',
  AWSManagedRulesAnonymousIpList = 'AWSManagedRulesAnonymousIpList',
  AWSManagedRulesBotControlRuleSet = 'AWSManagedRulesBotControlRuleSet',
  AWSManagedRulesAccountTakeoverPreventionRuleSet = 'AWSManagedRulesAccountTakeoverPreventionRuleSet',
  AWSManagedRulesAccountCreationFraudPreventionRuleSet = 'AWSManagedRulesAccountCreationFraudPreventionRuleSet',
}

export enum CommonRuleSetExcludedRule {
  NoUserAgent_HEADER = 'NoUserAgent_HEADER',
  UserAgent_BadBots_HEADER = 'UserAgent_BadBots_HEADER',
  SizeRestrictions_QUERYSTRING = 'SizeRestrictions_QUERYSTRING',
  SizeRestrictions_Cookie_HEADER = 'SizeRestrictions_Cookie_HEADER',
  SizeRestrictions_BODY = 'SizeRestrictions_BODY',
  SizeRestrictions_URIPATH = 'SizeRestrictions_URIPATH',
  EC2MetaDataSSRF_BODY = 'EC2MetaDataSSRF_BODY',
  EC2MetaDataSSRF_COOKIE = 'EC2MetaDataSSRF_COOKIE',
  EC2MetaDataSSRF_URIPATH = 'EC2MetaDataSSRF_URIPATH',
  EC2MetaDataSSRF_QUERYARGUMENTS = 'EC2MetaDataSSRF_QUERYARGUMENTS',
  GenericLFI_QUERYARGUMENTS = 'GenericLFI_QUERYARGUMENTS',
  GenericLFI_URIPATH = 'GenericLFI_URIPATH',
  GenericLFI_BODY = 'GenericLFI_BODY',
  RestrictedExtensions_URIPATH = 'RestrictedExtensions_URIPATH',
  RestrictedExtensions_QUERYARGUMENTS = 'RestrictedExtensions_QUERYARGUMENTS',
  GenericRFI_QUERYARGUMENTS = 'GenericRFI_QUERYARGUMENTS',
  GenericRFI_BODY = 'GenericRFI_BODY',
  GenericRFI_URIPATH = 'GenericRFI_URIPATH',
  CrossSiteScripting_COOKIE = 'CrossSiteScripting_COOKIE',
  CrossSiteScripting_QUERYARGUMENTS = 'CrossSiteScripting_QUERYARGUMENTS',
  CrossSiteScripting_BODY = 'CrossSiteScripting_BODY',
  CrossSiteScripting_URIPATH = 'CrossSiteScripting_URIPATH',
}